/// Translation Editor — side-by-side EN reference vs. target language.
///
/// Shows all translation keys from the English reference TOML, lets the user
/// edit the target language values inline, and provides:
///   - Progress bar (translated / total keys)
///   - "Export .toml" for everyone
///   - "Commit & Push" for authenticated GitHub contributors
use dioxus::prelude::*;
use fsn_i18n;
use fsn_manager_language::git_contributor::{ContributorStatus, GitContributorCheck};

// ── Reference TOML (compile-time) ─────────────────────────────────────────────

const EN_TOML: &str = include_str!("../assets/i18n/en.toml");

// ── TranslationEntry ──────────────────────────────────────────────────────────

/// One key-value pair from a translation file.
#[derive(Clone, PartialEq, Debug)]
struct TranslationEntry {
    key:        String,
    en_value:   String,
    /// Current value in the target language (empty string = untranslated).
    target_val: String,
    edited:     bool,
}

impl TranslationEntry {
    fn is_translated(&self) -> bool {
        !self.target_val.is_empty()
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Flattens a TOML table into a list of `"section.key" = "value"` pairs.
fn flatten_toml(toml_str: &str) -> Vec<(String, String)> {
    let Ok(table) = toml_str.parse::<toml::Table>() else {
        return Vec::new();
    };
    let mut out = Vec::new();
    flatten_table(&table, String::new(), &mut out);
    out
}

fn flatten_table(table: &toml::Table, prefix: String, out: &mut Vec<(String, String)>) {
    for (k, v) in table {
        let full_key = if prefix.is_empty() {
            k.clone()
        } else {
            format!("{prefix}.{k}")
        };
        match v {
            toml::Value::String(s) => out.push((full_key, s.clone())),
            toml::Value::Table(t)  => flatten_table(t, full_key, out),
            other                  => out.push((full_key, other.to_string())),
        }
    }
}

/// Renders `Vec<TranslationEntry>` back to a TOML string (flat key = "value" format).
fn entries_to_toml(entries: &[TranslationEntry]) -> String {
    let mut lines = vec![
        "# FreeSynergy translation".to_string(),
        "# Generated by Translation Editor".to_string(),
        String::new(),
    ];
    for e in entries {
        if e.is_translated() {
            let escaped = e.target_val.replace('\\', r"\\").replace('"', r#"\""#);
            lines.push(format!("{} = \"{}\"", e.key, escaped));
        }
    }
    lines.join("\n")
}

/// Loads the installed translation for `lang_code` from
/// `~/.local/share/fsn/i18n/{lang_code}/ui.toml`.
fn load_installed_translation(lang_code: &str) -> Vec<(String, String)> {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
    let path = std::path::PathBuf::from(home)
        .join(".local/share/fsn/i18n")
        .join(lang_code)
        .join("ui.toml");
    let content = std::fs::read_to_string(path).unwrap_or_default();
    flatten_toml(&content)
}

/// Builds the merged entry list (EN reference + existing target values).
fn build_entries(lang_code: &str) -> Vec<TranslationEntry> {
    let en_pairs  = flatten_toml(EN_TOML);
    let tgt_pairs = load_installed_translation(lang_code);
    let tgt_map: std::collections::HashMap<String, String> = tgt_pairs.into_iter().collect();

    en_pairs
        .into_iter()
        .map(|(key, en_value)| {
            let target_val = tgt_map.get(&key).cloned().unwrap_or_default();
            TranslationEntry { key, en_value, target_val, edited: false }
        })
        .collect()
}

// ── TranslationEditor ─────────────────────────────────────────────────────────

/// Props for the Translation Editor.
#[component]
pub fn TranslationEditor(
    /// Language code to translate into (e.g. "fr", "ja").
    lang_code:   String,
    /// Display name of the target language.
    lang_name:   String,
    /// Called when the user closes/hides the editor.
    on_close:    EventHandler<()>,
) -> Element {
    let mut entries      = use_signal(|| build_entries(&lang_code));
    let mut filter_empty = use_signal(|| false);
    let mut search_query = use_signal(String::new);

    // Git contributor status — start with cache, refresh in background.
    let mut contrib = use_signal(|| {
        GitContributorCheck::cached().unwrap_or(ContributorStatus::Unknown)
    });

    // Trigger background SSH check if status is Unknown.
    {
        let mut contrib = contrib.clone();
        use_future(move || async move {
            if *contrib.read() == ContributorStatus::Unknown {
                let result = GitContributorCheck::check_and_cache();
                contrib.set(result);
            }
        });
    }

    // Push state.
    let mut push_msg = use_signal(|| Option::<Result<String, String>>::None);

    // Derived counts.
    let total      = entries.read().len();
    let translated = entries.read().iter().filter(|e| e.is_translated()).count();
    let pct        = if total > 0 { (translated * 100) / total } else { 0 };

    // Displayed entries (filtered).
    let query = search_query.read().to_lowercase();
    let show_empty = *filter_empty.read();
    let visible: Vec<(usize, TranslationEntry)> = entries
        .read()
        .iter()
        .enumerate()
        .filter(|(_, e)| {
            let matches_filter = !show_empty || !e.is_translated();
            let matches_search = query.is_empty()
                || e.key.to_lowercase().contains(&query)
                || e.en_value.to_lowercase().contains(&query);
            matches_filter && matches_search
        })
        .map(|(i, e)| (i, e.clone()))
        .collect();

    rsx! {
        div {
            style: "display: flex; flex-direction: column; height: 100%; \
                    background: var(--fsn-color-bg-default);",

            // ── Header ────────────────────────────────────────────────────────
            div {
                style: "padding: 16px 20px; border-bottom: 1px solid var(--fsn-color-border-default); \
                        display: flex; align-items: center; gap: 12px; flex-shrink: 0;",

                button {
                    style: "background: none; border: none; cursor: pointer; \
                            font-size: 18px; color: var(--fsn-color-text-muted); padding: 0;",
                    onclick: move |_| on_close.call(()),
                    "←"
                }
                div { style: "flex: 1;",
                    h3 {
                        style: "margin: 0; font-size: 15px;",
                        {fsn_i18n::t("settings.language.editor.title")}
                        span {
                            style: "margin-left: 8px; font-size: 13px; \
                                    color: var(--fsn-color-primary); font-weight: 400;",
                            "{lang_name} ({lang_code})"
                        }
                    }
                }

                // Git contributor badge
                {
                    let (badge_label, badge_style) = match contrib.read().clone() {
                        ContributorStatus::Authenticated { github_user } => (
                            format!("GitHub: {github_user}"),
                            "background: rgba(34,197,94,0.15); color: #16a34a; \
                             border: 1px solid rgba(34,197,94,0.4);",
                        ),
                        ContributorStatus::NotAuthenticated => (
                            fsn_i18n::t("settings.language.editor.no_ssh"),
                            "background: rgba(156,163,175,0.15); color: var(--fsn-color-text-muted); \
                             border: 1px solid var(--fsn-color-border-default);",
                        ),
                        ContributorStatus::Unknown => (
                            fsn_i18n::t("settings.language.editor.checking_ssh"),
                            "background: rgba(234,179,8,0.15); color: #ca8a04; \
                             border: 1px solid rgba(234,179,8,0.4);",
                        ),
                    };
                    rsx! {
                        span {
                            style: "font-size: 11px; padding: 3px 10px; \
                                    border-radius: 999px; white-space: nowrap; {badge_style}",
                            "{badge_label}"
                        }
                    }
                }
            }

            // ── Progress bar ──────────────────────────────────────────────────
            div { style: "padding: 12px 20px; border-bottom: 1px solid var(--fsn-color-border-default); \
                          flex-shrink: 0;",
                div {
                    style: "display: flex; justify-content: space-between; \
                            font-size: 12px; color: var(--fsn-color-text-muted); margin-bottom: 6px;",
                    span { {fsn_i18n::t_with("settings.language.editor.progress",
                                &[("done", &translated.to_string()),
                                  ("total", &total.to_string())])} }
                    span { "{pct}%" }
                }
                div {
                    style: "height: 6px; background: var(--fsn-color-bg-surface); \
                            border-radius: 999px; overflow: hidden;",
                    div {
                        style: "height: 100%; width: {pct}%; \
                                background: var(--fsn-color-primary); \
                                border-radius: 999px; transition: width 0.3s;",
                    }
                }
            }

            // ── Toolbar ───────────────────────────────────────────────────────
            div {
                style: "padding: 10px 20px; display: flex; gap: 10px; align-items: center; \
                        border-bottom: 1px solid var(--fsn-color-border-default); flex-shrink: 0;",

                // Search
                input {
                    style: "flex: 1; padding: 6px 10px; font-size: 13px; \
                            background: var(--fsn-color-bg-surface); \
                            border: 1px solid var(--fsn-color-border-default); \
                            border-radius: var(--fsn-radius-sm); \
                            color: var(--fsn-color-text-primary);",
                    r#type: "text",
                    placeholder: fsn_i18n::t("settings.language.editor.search_placeholder"),
                    value: "{search_query}",
                    oninput: move |e| search_query.set(e.value()),
                }

                // Filter: missing only
                label {
                    style: "display: flex; align-items: center; gap: 6px; \
                            font-size: 12px; cursor: pointer; white-space: nowrap; \
                            color: var(--fsn-color-text-muted);",
                    input {
                        r#type: "checkbox",
                        checked: *filter_empty.read(),
                        onchange: move |_| {
                            let cur = *filter_empty.read();
                            filter_empty.set(!cur);
                        },
                    }
                    {fsn_i18n::t("settings.language.editor.show_missing")}
                }

                // Visible count
                span {
                    style: "font-size: 11px; color: var(--fsn-color-text-muted);",
                    {fsn_i18n::t_with("settings.language.editor.showing",
                        &[("n", &visible.len().to_string())])}
                }
            }

            // ── Key list ──────────────────────────────────────────────────────
            div {
                style: "flex: 1; overflow-y: auto; scrollbar-width: thin;",

                // Column header
                div {
                    style: "display: grid; grid-template-columns: 200px 1fr 1fr; \
                            gap: 0; padding: 8px 20px; \
                            background: var(--fsn-color-bg-surface); \
                            border-bottom: 1px solid var(--fsn-color-border-default); \
                            font-size: 11px; font-weight: 600; \
                            color: var(--fsn-color-text-muted); text-transform: uppercase; \
                            letter-spacing: 0.05em; position: sticky; top: 0; z-index: 1;",
                    span { {fsn_i18n::t("settings.language.editor.col_key")} }
                    span { "English" }
                    span { "{lang_name}" }
                }

                for (idx, entry) in visible {
                    TranslationRow {
                        key: "{idx}",
                        entry: entry.clone(),
                        on_change: {
                            let mut entries = entries.clone();
                            move |new_val: String| {
                                entries.write()[idx].target_val = new_val;
                                entries.write()[idx].edited     = true;
                            }
                        },
                    }
                }
            }

            // ── Action bar ────────────────────────────────────────────────────
            div {
                style: "padding: 14px 20px; border-top: 1px solid var(--fsn-color-border-default); \
                        display: flex; align-items: center; gap: 12px; flex-shrink: 0;",

                // Export .toml
                button {
                    style: "padding: 8px 18px; background: var(--fsn-color-bg-surface); \
                            border: 1px solid var(--fsn-color-border-default); \
                            border-radius: var(--fsn-radius-md); font-size: 13px; \
                            cursor: pointer; color: var(--fsn-color-text-primary);",
                    onclick: {
                        let entries = entries.clone();
                        let lang_code = lang_code.clone();
                        move |_| {
                            let toml_str = entries_to_toml(&entries.read());
                            let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
                            let dest = std::path::PathBuf::from(&home)
                                .join("Downloads")
                                .join(format!("fsn-{lang_code}.toml"));
                            let _ = std::fs::create_dir_all(dest.parent().unwrap());
                            let _ = std::fs::write(&dest, &toml_str);
                            // Also install locally so the user can preview immediately.
                            let install_dir = std::path::PathBuf::from(&home)
                                .join(".local/share/fsn/i18n")
                                .join(&lang_code);
                            let _ = std::fs::create_dir_all(&install_dir);
                            let _ = std::fs::write(install_dir.join("ui.toml"), toml_str);
                        }
                    },
                    {fsn_i18n::t("settings.language.editor.btn_export")}
                }

                // Push to GitHub (contributor only)
                if let ContributorStatus::Authenticated { .. } = contrib.read().clone() {
                    button {
                        style: "padding: 8px 18px; background: var(--fsn-color-primary); \
                                color: white; border: none; \
                                border-radius: var(--fsn-radius-md); font-size: 13px; \
                                cursor: pointer;",
                        onclick: {
                            let entries    = entries.clone();
                            let lang_code  = lang_code.clone();
                            let mut push_msg = push_msg.clone();
                            move |_| {
                                let toml_str  = entries_to_toml(&entries.read());
                                let lang_code = lang_code.clone();
                                let toml_str2 = toml_str.clone();
                                let mut push_msg = push_msg.clone();
                                spawn(async move {
                                    // Look for a local Node repo clone. The user can set
                                    // FSN_NODE_REPO_PATH to point to their clone.
                                    let repo_path = std::env::var("FSN_NODE_REPO_PATH")
                                        .unwrap_or_else(|_| {
                                            let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
                                            format!("{home}/FreeSynergy.Node")
                                        });
                                    let result = fsn_manager_language::git_contributor::GitContributorCheck
                                        ::push_translation(
                                            std::path::Path::new(&repo_path),
                                            &lang_code,
                                            &toml_str2,
                                        );
                                    push_msg.set(Some(result));
                                });
                            }
                        },
                        {fsn_i18n::t("settings.language.editor.btn_push")}
                    }
                }

                // Re-check SSH
                button {
                    style: "padding: 8px 12px; background: none; border: none; \
                            font-size: 12px; color: var(--fsn-color-text-muted); \
                            cursor: pointer; text-decoration: underline;",
                    onclick: {
                        let mut contrib = contrib.clone();
                        move |_| {
                            GitContributorCheck::clear_cache();
                            contrib.set(ContributorStatus::Unknown);
                        }
                    },
                    {fsn_i18n::t("settings.language.editor.btn_recheck_ssh")}
                }

                // Push result message
                if let Some(result) = push_msg.read().as_ref() {
                    span {
                        style: {
                            let color = if result.is_ok() { "var(--fsn-color-success, #16a34a)" }
                                        else              { "var(--fsn-color-error, #dc2626)" };
                            format!("font-size: 12px; color: {color};")
                        },
                        {
                            match result {
                                Ok(msg)  => msg.clone(),
                                Err(err) => format!("Error: {err}"),
                            }
                        }
                    }
                }
            }
        }
    }
}

// ── TranslationRow ────────────────────────────────────────────────────────────

#[component]
fn TranslationRow(
    entry:     TranslationEntry,
    on_change: EventHandler<String>,
) -> Element {
    let row_bg = if entry.edited {
        "background: rgba(234,179,8,0.06);"
    } else if !entry.is_translated() {
        "background: rgba(220,38,38,0.04);"
    } else {
        "background: transparent;"
    };

    rsx! {
        div {
            style: "display: grid; grid-template-columns: 200px 1fr 1fr; \
                    gap: 0; padding: 0; \
                    border-bottom: 1px solid var(--fsn-color-border-default); \
                    {row_bg}",

            // Key column
            div {
                style: "padding: 8px 20px; font-size: 11px; font-family: monospace; \
                        color: var(--fsn-color-text-muted); word-break: break-all; \
                        border-right: 1px solid var(--fsn-color-border-default); \
                        display: flex; align-items: center;",
                span { "{entry.key}" }
            }

            // English reference column (read-only)
            div {
                style: "padding: 8px 12px; font-size: 13px; \
                        color: var(--fsn-color-text-secondary, var(--fsn-color-text-muted)); \
                        border-right: 1px solid var(--fsn-color-border-default); \
                        display: flex; align-items: center;",
                span { "{entry.en_value}" }
            }

            // Target language column (editable)
            div {
                style: "padding: 4px 8px; display: flex; align-items: center;",
                textarea {
                    style: "width: 100%; min-height: 32px; padding: 4px 6px; \
                            font-size: 13px; font-family: inherit; \
                            background: transparent; resize: none; \
                            border: 1px solid transparent; \
                            border-radius: var(--fsn-radius-sm); \
                            color: var(--fsn-color-text-primary); \
                            transition: border-color 0.1s;",
                    rows: "1",
                    placeholder: "…",
                    value: "{entry.target_val}",
                    oninput: move |e| on_change.call(e.value()),
                    onfocus: move |e: FocusEvent| {
                        // Visual focus via inline style is handled by CSS :focus
                        let _ = e;
                    },
                }
            }
        }
    }
}
