// fs-settings/src/translation_editor.rs — Translation editor logic.
//
// Provides helper functions for parsing FTL/TOML translation files
// and building LLM translation prompts.
// The iced UI is managed directly from language.rs (as a sub-view).

use std::fmt::Write as _;

use fs_manager_language::git_contributor::{ContributorStatus, GitContributorCheck};

use crate::service_roles::load_role_assignments;

// ── Reference FTL (compile-time) ──────────────────────────────────────────────

const EN_FTL: &str = include_str!("../../../../fs-i18n/locales/en/settings.ftl");

// ── TranslationEntry ──────────────────────────────────────────────────────────

/// One translation key/value pair in the editor.
#[derive(Clone, PartialEq, Debug)]
pub struct TranslationEntry {
    pub key: String,
    pub en_value: String,
    /// Current value in the target language (empty = untranslated).
    pub target_val: String,
    pub edited: bool,
}

impl TranslationEntry {
    #[must_use]
    pub fn is_translated(&self) -> bool {
        !self.target_val.is_empty()
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Parse a Fluent `.ftl` source and return all `(key, value)` pairs.
///
/// Handles simple message definitions: `key-name = Value text`.
/// Skips comments, blank lines, and multi-line attributes.
#[must_use]
pub fn flatten_ftl(ftl_src: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for line in ftl_src.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some(eq_pos) = trimmed.find(" = ") {
            let key = trimmed[..eq_pos].trim().to_string();
            let value = trimmed[eq_pos + 3..].trim().to_string();
            if !key.is_empty() && !value.is_empty() {
                out.push((key, value));
            }
        }
    }
    out
}

/// Serialize translation entries to TOML format.
#[must_use]
pub fn entries_to_toml(entries: &[TranslationEntry]) -> String {
    let mut lines = vec![
        "# FreeSynergy translation".to_string(),
        "# Generated by Translation Editor".to_string(),
        String::new(),
    ];
    for e in entries {
        if e.is_translated() {
            let escaped = e.target_val.replace('\\', r"\\").replace('"', r#"\""#);
            lines.push(format!("{} = \"{}\"", e.key, escaped));
        }
    }
    lines.join("\n")
}

/// Parse a TOML translation file from disk into flat `(key, value)` pairs.
#[must_use]
pub fn flatten_toml_file(toml_str: &str) -> Vec<(String, String)> {
    let Ok(table) = toml_str.parse::<toml::Table>() else {
        return Vec::new();
    };
    let mut out = Vec::new();
    flatten_toml_table(&table, "", &mut out);
    out
}

fn flatten_toml_table(table: &toml::Table, prefix: &str, out: &mut Vec<(String, String)>) {
    for (k, v) in table {
        let full_key = if prefix.is_empty() {
            k.clone()
        } else {
            format!("{prefix}.{k}")
        };
        match v {
            toml::Value::String(s) => out.push((full_key, s.clone())),
            toml::Value::Table(t) => flatten_toml_table(t, &full_key, out),
            other => out.push((full_key, other.to_string())),
        }
    }
}

/// Load installed translation for a language code from the user's data dir.
#[must_use]
pub fn load_installed_translation(lang_code: &str) -> Vec<(String, String)> {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
    let path = std::path::PathBuf::from(home)
        .join(".local/share/fsn/i18n")
        .join(lang_code)
        .join("ui.toml");
    let content = std::fs::read_to_string(path).unwrap_or_default();
    flatten_toml_file(&content)
}

/// Build translation entries by merging the EN reference FTL with installed translations.
#[must_use]
pub fn build_entries(lang_code: &str) -> Vec<TranslationEntry> {
    let en_pairs = flatten_ftl(EN_FTL);
    let tgt_pairs = load_installed_translation(lang_code);
    let tgt_map: std::collections::HashMap<String, String> = tgt_pairs.into_iter().collect();

    en_pairs
        .into_iter()
        .map(|(key, en_value)| {
            let target_val = tgt_map.get(&key).cloned().unwrap_or_default();
            TranslationEntry {
                key,
                en_value,
                target_val,
                edited: false,
            }
        })
        .collect()
}

// ── LLM helpers ───────────────────────────────────────────────────────────────

/// Auto-generates the LLM prompt: EN reference + missing keys.
#[must_use]
pub fn build_llm_prompt(
    lang_name: &str,
    lang_code: &str,
    entries: &[TranslationEntry],
    user_request: &str,
) -> String {
    let missing: Vec<&TranslationEntry> = entries
        .iter()
        .filter(|e| !e.is_translated())
        .take(50)
        .collect();

    let mut prompt = format!(
        "You are a professional software translator for the FreeSynergy open-source project.\n\
         Translate the following UI text strings into {lang_name} ({lang_code} locale).\n\
         Return ONLY a flat TOML block — one line per key, format: \"key.name\" = \"translation\"\n\
         No explanations, no code fences, no comments.\n\n\
         Strings to translate:\n"
    );

    for e in &missing {
        let escaped = e.en_value.replace('"', r#"\""#);
        let _ = writeln!(prompt, "\"{}\" = \"{}\"", e.key, escaped);
    }

    if !user_request.trim().is_empty() {
        let _ = write!(prompt, "\nAdditional instruction: {}", user_request.trim());
    }

    prompt
}

/// Parses the LLM response into `(key, value)` proposal pairs.
#[must_use]
pub fn parse_llm_proposals(response: &str) -> Vec<(String, String)> {
    let mut proposals = Vec::new();

    let body = response
        .trim()
        .trim_start_matches("```toml")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    for line in body.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(eq_pos) = line.find(" = \"") {
            let raw_key = line[..eq_pos].trim().trim_matches('"').to_string();
            let value_start = eq_pos + 4;
            if value_start < line.len() {
                let tail = &line[value_start..];
                let value = tail.trim_end_matches('"').to_string();
                if !raw_key.is_empty() {
                    proposals.push((raw_key, value));
                }
            }
        }
    }

    proposals
}

/// Check if the LLM role is configured.
#[must_use]
pub fn llm_service_name() -> Option<String> {
    let assignments = load_role_assignments();
    assignments.get("llm").map(std::string::ToString::to_string)
}

/// Check contributor status for the git integration.
/// Uses the local cache if available and not expired; otherwise runs a fresh SSH check.
#[must_use]
pub fn contributor_status() -> ContributorStatus {
    GitContributorCheck::cached().unwrap_or_else(GitContributorCheck::check_and_cache)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flatten_ftl_parses_simple_keys() {
        let ftl = "hello = Hello World\nfoo-bar = Foo Bar\n";
        let pairs = flatten_ftl(ftl);
        assert_eq!(pairs.len(), 2);
        assert_eq!(pairs[0], ("hello".to_string(), "Hello World".to_string()));
    }

    #[test]
    fn flatten_ftl_skips_comments_and_blanks() {
        let ftl = "# comment\n\nhello = Hi\n";
        let pairs = flatten_ftl(ftl);
        assert_eq!(pairs.len(), 1);
    }

    #[test]
    fn entries_to_toml_only_translated() {
        let entries = vec![
            TranslationEntry {
                key: "hello".to_string(),
                en_value: "Hello".to_string(),
                target_val: "Hallo".to_string(),
                edited: false,
            },
            TranslationEntry {
                key: "bye".to_string(),
                en_value: "Bye".to_string(),
                target_val: String::new(),
                edited: false,
            },
        ];
        let toml = entries_to_toml(&entries);
        assert!(toml.contains("hello"));
        assert!(!toml.contains("bye"));
    }

    #[test]
    fn parse_llm_proposals_basic() {
        let response = r#""foo.bar" = "Translated""#;
        let proposals = parse_llm_proposals(response);
        assert_eq!(proposals.len(), 1);
        assert_eq!(proposals[0].0, "foo.bar");
        assert_eq!(proposals[0].1, "Translated");
    }
}
